config/routes.rb
Rails.application.routes.draw do
  root to: 'statics#top'
  # statics routes
  get "/terms_of_service",  to: "statics#tos",  as: :tos
  get "/privacy_policy",    to: "statics#pp",   as: :pp

  # Auth0 routes
  get     "/auth/auth0/callback", to: "auth0#callback", as: :auth0_callback
  get     "/auth/failure",        to: "auth0#failure",  as: :auth0_failure
  delete  "/auth/logout",         to: "auth0#logout",   as: :auth0_logout

  # Article pages
  get     "/articles",            to: "articles#index",   as: :articles
  post    "/articles",            to: "articles#create",  as: :create_articles
  delete  "/articles/:id",        to: "articles#destroy", as: :delete_article
  get     "/articles/:id/edit",   to: "articles#edit",    as: :edit_article
  patch   "/articles/:id/edit",   to: "articles#update",  as: :update_article

  # active admin
  ActiveAdmin.routes(self)
end

app/models/article.rb
class Article < ApplicationRecord
  # Associations
  has_many :user_articles, dependent: :destroy
  has_many :users, through: :user_articles


  before_validation :strip_all_space_from_url
  before_save :set_ogp_info

  validates :url,
    format: { with: /\A#{URI::regexp(%w(http https))}\z/, message: "に https:// または http:// から始まる文字列を入力してください" },
    length: { maximum: 2000 },
    uniqueness: true

  private
    def strip_all_space_from_url
      self.url.gsub!(/(^[[:space:]]+)|([[:space:]]+$)/, '')
    end

    def set_ogp_info
      begin
        res = Faraday.get(self.url)
        doc = Nokogiri::HTML.parse(res.body)
      rescue
        self.errors.add(:url, "のページは存在しないようです")
        throw :abort
      end

      # title
      if (title = doc.xpath("//meta[@property='og:title']/@content").to_s).present?
        self.title = title
      elsif (title = doc.xpath("//meta[@name='title']/@content").to_s).present?
        self.title = title
      elsif (title = doc.title).present?
        self.title = title
      else
        self.title = self.url
      end

      # image_url
      if (image_url = doc.xpath("//meta[@property='og:image']/@content").first.to_s).present?
        self.image_url = image_url 
      end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :redirect_unless_logged_in
  before_action :set_articles, only: [:index, :create]
  before_action :set_user_article, only: [:edit, :update]

  def index
    @article = Article.new
  end

  def create
    @article = Article.find_by(url: article_params[:url])
    @article ||= Article.new(article_params)

    if @article.save
      user_article = UserArticle.new
      user_article.user = current_user
      user_article.article = @article

      if user_article.save
        redirect_to articles_path(type: :reading_later)
      else
        @article.errors.add(:base, :already_registered, message: "この記事はすでに登録されています")
        render :index
      end

    else
      render :index
    end
  end

  def edit
  end

  def update
    redirect_link_type = :finish_reading
    pixela_flag = false
    @user_article.assign_attributes(user_article_params)
    
    # あとで読むリストの記事だった場合
    if @user_article.finish_reading_at.blank?
      @user_article.finish_reading_at = Time.now
      redirect_link_type = :reading_later
      pixela_flag = true
    end

    if @user_article.save
      if pixela_flag && !Rails.env.test?
        res = Faraday.put("#{ENV['PIXELA_BASE_URL']}/graphs/#{current_user.id}/increment") do |req|
          req.headers["X-USER-TOKEN"] = ENV["PIXELA_X_USER_TOKEN"]
          req.headers["Content-Length"] = 0
        end
        unless res.success?
          puts "Faraday failed when finish reading."
          puts "status: #{res.status}"
          puts "headers: #{res.headers}"
          puts "body: #{res.body}"
        end
      end
      redirect_to articles_path(type: redirect_link_type)
    else
      render :edit
    end
  end

  def destroy
    user_article = UserArticle.find_by(id: params[:id], user_id: current_user.id)
    unless user_article.nil?
      article = user_article.article
      user_article.destroy
      article.destroy if article.user_articles.blank?
    end
    redirect_to articles_path(type: :reading_later)
  end

  private
    def article_params
      params.require(:article).permit(:url)
    end

    def user_article_params
      params.require(:user_article).permit(:memo)
    end

    def set_articles
      case params[:type]
      when "reading_later"
        @user_articles = current_user.user_articles.where(finish_reading_at: nil).order(created_at: :asc)
      when "finish_reading"
        @user_articles = current_user.user_articles.where.not(finish_reading_at: nil).order(finish_reading_at: :desc)
      else
        redirect_to articles_path(type: :reading_later)
      end
    end

    def set_user_article
      @user_article = UserArticle.find_by(id: params[:id], user_id: current_user.id)
      redirect_to articles_path(type: :reading_latter) if @user_article.nil?
      @article = @user_article.article unless @user_article.nil?
    end
end

app/views/articles/_add_article_form.html.erb
<%= form_with model: @article, url: articles_path(type: params[:type]), method: :post, local: true, class: "mb-3" do |form| %>
  <div class="field">
    <div class="control has-icons-left">
      <%= form.text_field :url, class: "input", placeholder: "URL" %>
      <span class="icon is-small is-left"><i class="fas fa-link"></i></span>
    </div>
  </div>
  <div class="field">
    <div class="control has-text-centered">
      <button type="submit" id="create_article_button" class="button is-primary is-outlined is-rounded">
        <span class="icon"><i class="fas fa-plus-circle"></i></span>
        <% if params[:type] == "reading_later" %>
          <span>あとで読む！</span>
        <% elsif params[:type] == "finish_reading" %>
          <span>読了！</span>
        <% end %>
      </button>
    </div>
  </div>
<% end %>

app/views/articles/_article_card.html.erb
<div class="card article-card grid-item my-3">
  <%= link_to article.url, target: "_blank" do %>
    <header class="card-header">
      <p class="card-header-title"><%= article.title %></p>
    </header>
    <div class="card-image has-background-light">
      <figure class="image">
        <% if article.image_url.present? %>
          <%= image_tag article.image_url %>
        <% else %>
          <%= image_tag "no_image.png" %>
        <% end %>
      </figure>
    </div>
  <% end %>
  <% if memo_visible and user_article.memo.present? %>
    <div class="card-content article-memo has-text-dark"><%= safe_join(user_article.memo.split("\n"), tag(:br)) %></div>
  <% end %>
  <footer class="card-footer">
    <% case params[:type] %>
    <% when "reading_later" %>
      <%= link_to "読了！", edit_article_path(user_article), class: "finish-reading-button card-footer-item has-background-primary has-text-white has-text-weight-bold" %>
      <%= link_to "削除", delete_article_path(user_article), method: :delete, class: "card-footer-item has-text-danger card-delete-button", data: {confirm: "#{article.title}を削除しますか？"} %>
    <% when "finish_reading" %>
      <%= link_to "メモ編集", edit_article_path(user_article), class: "edit-memo-button card-footer-item" %>
      <% tweet_text = user_article.memo.present? ? "#{user_article.memo}" : "読みました！" %>
      <% tweet_text += "\n\n#Learticle\n" %>
      <%= link_to "https://twitter.com/intent/tweet?text=#{CGI.escape(tweet_text)}&url=#{CGI.escape(article.url)}", class: "article-tweet-button card-footer-item has-text-white", style: "background-color: #1DA1F2;", target: "_blank" do %>
        <i class="fab fa-twitter"></i>
      <% end %>
    <% end %>
  </footer>
</div>

app/views/articles/_error_message.html.erb
<% if model.errors.present? %>
  <div id="error_message_area" class="message is-danger">
    <ul class="message-body">
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/articles/_tab.html.erb
<div class="tabs is-centered is-boxed">
  <ul>
    <li class=<%= "is-active" if params[:type] == "reading_later" %>>
      <%= link_to articles_path(type: :reading_later), id: :reading_later_tab do %>
        <span class="icon is-small"><i class="far fa-bookmark"></i></span>
        <span>あとで読む</span>
      <% end %>
    </li>
    <li class=<%= "is-active" if params[:type] == "finish_reading" %>>
      <%= link_to articles_path(type: :finish_reading), id: :finish_reading_tab do %>
        <span class="icon is-small"><i class="fas fa-check"></i></span>
        <span>読了</span>
      <% end %>
    </li>
  </ul>
</div>

app/views/articles/edit.html.erb
<section class="section">
  <div class="container" style="max-width: 640px;">
    <div class="level">
      <div class="level-item" style="max-width: 640px;">
        <%= render "article_card", user_article: @user_article, article: @article, memo_visible: false %>
      </div>
    </div>
    <%= form_with model: @user_article, url: update_article_path(@user_article), local: true, class: "mb-3" do |form| %>
      <%= render "error_message", model: @user_article %>
      <div class="field has-text-left">
        <%= form.label :memo, class: "label" %>
        <div class="control">
          <%= form.text_area :memo, class: "textarea", autofocus: true %>
        </div>
      </div>
      <div class="has-text-centered mt-3">
        <div class="buttons is-centered">
          <button type="submit" id="update_article_button" class="button is-primary has-text-weight-bold mr-2">
            <span class="icon">
              <i class="fas fa-check"></i>
            </span>
            <span>登録！</span>
          </button>
          <button type="button" id="tweet_button" class="button has-text-white" style="background-color: #1DA1F2;" onClick="move_to_tweet();">
            <span class="icon">
              <i class="fab fa-twitter"></i>
            </span>
            <span>ツイート</span>
          </button>
        </div>
        <% back_link = @user_article.finish_reading_at.present? ? articles_path(type: :finish_reading) : articles_path(type: :reading_later) %>
        <%= link_to "戻る", back_link, id: :cancel_link, class: "button is-white" %>
      </div>
    <% end %>
  </div>
</section>

<script>
  function move_to_tweet() {
    var memo = document.getElementById("user_article_memo").value;
    if (!memo) { memo = "読みました！"; }
    text = encodeURIComponent(memo + "\n\n#Learticle");
    const url = <%== JSON.dump(CGI.escape(@article.url)) %>;
    const href = "https://twitter.com/intent/tweet?text=" + text + "&url=" + url;
    window.open(href, "_blank");
  }
</script>

app/views/articles/index.html.erb
<section class="section">
  <div class="container">
    <%= render "tab" %>
    
    <% case params[:type] %>
    <% when "reading_later" %>
      <%= render "error_message", model: @article %>
      <%= render "add_article_form", article: @article %>
    <% when "finish_reading" %>
      <% unless Rails.env.test? %>
        <div class="iframe-wrapper">
          <iframe src=<%= "#{ENV["PIXELA_BASE_URL"]}/graphs/#{current_user.id}.html?mode=simple" %> frameborder="0" scrolling="no"></iframe>
        </div>
      <% end %>
    <% end %>

    <p class="has-text-right">
      <%= params[:type] == "finish_reading" ? "読了記事数" : "あとで読む記事数"  %>：<span class="is-size-3 has-text-primary has-text-weight-bold"><%= @user_articles.count %></span>
    </p>

    <% if @user_articles.present? %>
      <div id="article_cards" class="grid" data-masonry='{ "itemSelector": ".grid-item", "columnWidth": ".grid-sizer", "gutter": 16, "percentPosition": false, "fitWidth": true }'>
        <div class="grid-sizer"></div>
        <% @user_articles.each do |user_article| %>
          <%= render "article_card", user_article: user_article, article: user_article.article, memo_visible: true %>
        <% end %>
      </div>
    <% end %>
  </div>
</section>

<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>