config/routes.rb
Rails.application.routes.draw do
  root to: 'statics#top'
  # statics routes
  get "/terms_of_service",  to: "statics#tos",  as: :tos
  get "/privacy_policy",    to: "statics#pp",   as: :pp

  # Auth0 routes
  get     "/auth/auth0/callback", to: "auth0#callback", as: :auth0_callback
  get     "/auth/failure",        to: "auth0#failure",  as: :auth0_failure
  delete  "/auth/logout",         to: "auth0#logout",   as: :auth0_logout

  # Article pages
  get     "/articles",            to: "articles#index",   as: :articles
  post    "/articles",            to: "articles#create",  as: :create_articles
  delete  "/articles/:id",        to: "articles#destroy", as: :delete_article
  get     "/articles/:id/edit",   to: "articles#edit",    as: :edit_article
  patch   "/articles/:id/edit",   to: "articles#update",  as: :update_article

  # active admin
  ActiveAdmin.routes(self)
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% if Rails.env.production? %>
      <!-- Global site tag (gtag.js) - Google Analytics -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=UA-168412277-1"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-168412277-1');
      </script>
      <!-- Global site tag (gtag.js) - Google Analytics -->
    <% end %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= display_meta_tags(default_meta_tags) %>
    <%= render 'application/favicon' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar is-primary" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to logged_in? ? articles_path(type: :reading_later) : root_path, id: :logo, class: "navbar-item title" do %>
          <% image_tag "logo.svg" %>
        <% end %>
      </div>
      <div class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <% if logged_in? %>
              <%= link_to "Logout", auth0_logout_path, method: :delete, id: :logout_button, class: "button is-primary" %>
            <% else %>
              <%= link_to "Login", "auth/auth0", method: :post, id: :login_button, class: "button is-primary has-text-weight-bold" %>
            <% end %>
          </div>
        </div>
      </div>
    </nav>

    <%= yield %>

    <footer class="footer has-text-centered">
      <div class="mb-1">
        <%= link_to_unless_current "利用規約", tos_path, id: :tos_link %>
        <span> | </span>
        <%= link_to_unless_current "プライバシーポリシー", pp_path, id: :pp_link %>
      </div>
      <p>Learticle by <%= link_to "at", "https://twitter.com/at_946" %>.</p>
    </footer>
  </body>
</html>